#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
import sys

GPIO.setmode(GPIO.BCM)
GPIO.setup(18, GPIO.OUT)
GPIO.setwarnings(False)

degree = int(sys.argv[1])
duty = float(degree) / 10 + 5

pwm=GPIO.PWM(18,100)
pwm.start(5)

pwm.ChangeDutyCycle(duty)
time.sleep(0.8)

GPIO.cleanup()
